### PR TITLE
Add test boundary and submissions

### LINKED ISSUE #106: Add Sample Submissions
## Overview

In order to mock out the rest of the application, we need some sample submissions in the system.

- Add three submissions, all authored by `c1@azavea.com`.
  - The first should be in `Draft` state.
  - The second should be in `Submitted` state.
  - The final should be in `Approved` state, approved by `v1@azavea.com`.
- They should all have different polygons so that they may be visually distinct.
- They may all correspond to the same utility.
- They should all have a different `created_at` date (days apart is fine)
- The `Approved` should be the oldest, then the `Submitted`, then the `Draft`
- There should be enough realistic data for each to compile an Activity Log for each
- `Submitted` and `Approved` ones should also have Notes attached for Submission

### PR DESCRIPTION
**Pull request by jacobtylerwalls**
## Overview
Add three mock submissions (a draft, a submission, and an approved submission) in order to continue mocking the app. For development only.

Closes #106

### Demo
Screen Shot 2022-10-06 at 4 42 07 PM

## Testing Instructions

- scripts/resetdb
- Use the Django admin to view the test submissions, verify acceptance criteria in #106

The Django admin does not have all relevant fields enabled, so to be super thorough, you could open `scripts/manage shell` and do something like:

<details>

```python
>>> from pprint import pprint
>>> from api.models.submission import Submission
>>> for s in Submission.objects.all():
...   pprint(vars(s))
... 
{'_state': <django.db.models.base.ModelState object at 0xffff99882fd0>,
 'boundary_id': 1,
 'created_at': datetime.datetime(2022, 10, 6, 20, 37, 19, 829320, tzinfo=<UTC>),
 'created_by_id': 3,
 'id': 1,
 'notes': '',
 'shape': <Polygon object at 0xffff9987c390>,
 'submitted_at': None,
 'submitted_by_id': None,
 'updated_at': datetime.datetime(2022, 10, 6, 20, 37, 19, 829333, tzinfo=<UTC>),
 'upload_edited_at': None,
 'upload_filename': ''}
{'_state': <django.db.models.base.ModelState object at 0xffff99882a00>,
 'boundary_id': 1,
 'created_at': datetime.datetime(2022, 10, 6, 20, 37, 19, 832722, tzinfo=<UTC>),
 'created_by_id': 3,
 'id': 2,
 'notes': 'Notes for the test submission.',
 'shape': <Polygon object at 0xffff9987c710>,
 'submitted_at': datetime.datetime(2022, 10, 2, 12, 0, tzinfo=<UTC>),
 'submitted_by_id': 3,
 'updated_at': datetime.datetime(2022, 10, 6, 20, 37, 19, 832736, tzinfo=<UTC>),
 'upload_edited_at': None,
 'upload_filename': ''}
{'_state': <django.db.models.base.ModelState object at 0xffff995670a0>,
 'boundary_id': 1,
 'created_at': datetime.datetime(2022, 10, 6, 20, 37, 19, 835451, tzinfo=<UTC>),
 'created_by_id': 3,
 'id': 3,
 'notes': 'Notes for the test approved boundary.',
 'shape': <Polygon object at 0xffff9987c410>,
 'submitted_at': datetime.datetime(2022, 10, 1, 9, 0, tzinfo=<UTC>),
 'submitted_by_id': 3,
 'updated_at': datetime.datetime(2022, 10, 6, 20, 37, 19, 835465, tzinfo=<UTC>),
 'upload_edited_at': None,
 'upload_filename': ''}
```
</details>

## Checklist

- [x] `fixup!` commits have been squashed
- [x] `CHANGELOG.md` updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [x] `README.md` updated if necessary to reflect the changes
- [x] CI passes after rebase

### CODE REVIEW

**Review by rachelekm — APPROVED** [review]
Looks great! Ran the recommended shell commands as well and confirmed `Submission` details are as expected. I've previously worked on projects where the `constants.py` file housed static functions and constants used within functionality vs to populate default data, so it might help it rename it or house it in a `/data` directory for clarity. It makes sense for `src/django/data` to continue to be git ignored, but maybe a `src/django/api/data` directory as we build default data? What do you think?

**Comment by jacobtylerwalls** [comment]
Agreed, I wasn't thrilled about using constants.py myself. I think the existing `src/django/data` would be alright to reuse.

**Comment by jacobtylerwalls** [comment]
Oh right. As in, we need a directory that _isn't_ git ignored.

**Comment by jacobtylerwalls** [comment]
Great idea. I moved the constants one level up from the only place they are used (the management commands). The file is not a command, so I didn't want it in `/commands`.

**Pull request merged**
