### PR TITLE
Update dev database configuration

### LINKED ISSUE #98: `./scripts/console database` fails with `role "postgres" does not exist`
## Overview

```
% ./scripts/console database
psql: error: could not connect to server: FATAL:  role "postgres" does not exist
```

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Rename the database container to `iow-boundary-tool` to match the rest of the app.
Switch to using PostGIS 3.1 / Postgres 12 version of the standard images rather than the Azavea ones, which is now the new standard. This is the same version as used in staging:

```console
./scripts/manage ecsmanage dbshell -- -c "SELECT PostGIS_Version();"
```

image

Closes #98 

### Demo

image

## Testing Instructions

- Checkout this branch
- Run `docker compose down` to delete all existing containers
- Run `./scripts/setup`
- Run `./scripts/console database`
  - [x] Ensure you can get in to `psql` and can run queries

## Checklist

- [x] `fixup!` commits have been squashed
- [x] `CHANGELOG.md` updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [ ] `README.md` updated if necessary to reflect the changes
- [ ] CI passes after rebase

### CODE REVIEW

**Comment by rajadain** [comment]
Sorry, had never pushed up the correct version number. This should fix it.

**Review by jacobtylerwalls — APPROVED** [review]
All good now!
[Edit: deleted remark about version numbers, as this was a symptom of not having pulled the latest changes]

**Comment by jacobtylerwalls** [comment]
Taking a look now -- I may not have run the test case correctly. One moment.

**Review by jacobtylerwalls — CHANGES_REQUESTED** [review]
Sorry, I assumed I could run the test case quickly at the end of standup. Instead, I'm finding  I'm still seeing the problem with 81521a951cb6ebd04ce492b72b20fabef4ef864a, where `scripts/update --docker` fails the first time after `docker compose down`.

**Comment by rajadain** [comment]
Noticed that the database container was taking longer to spin up the first time, installing PostGIS extension, etc, so increased the healthcheck retries in [1f45cc0](https://github.com/azavea/iow-boundary-tool/pull/121/commits/1f45cc03da0cd008b198a490af7db603ac55081c) to allow for that. Can you test on your end to see if it works now?

https://user-images.githubusercontent.com/1430060/195643669-4ef307b8-5fb2-42f3-a1a4-0640424c763c.mp4

**Review by jacobtylerwalls — APPROVED** [review]
Terrific! On your branch, `scripts/setup --docker` now succeeds the first time after `docker compose down`.

**Pull request merged**
