### PR TITLE
Fix add polygon

### LINKED ISSUE #167: Cannot draw shape
## Overview

Cannot draw new polygon in Draw page

### PR DESCRIPTION
**Pull request by mstone121**
## Overview

This PR addresses a few issues with the add polygon feature:
- The initial polygon wasn't loading because its lat and lng were reversed.
- The UI stays in add polygon mode after selecting a location

Closes #167 

## Testing Instructions

* Logout
* Go to http://localhost:4545
* Login as c1@azavea.com
* Select other utility
* Click through to draw page
- [x] Ensure add polygon works as expected

## Checklist

- [x] `fixup!` commits have been squashed
- [x] `CHANGELOG.md` updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [ ] `README.md` updated if necessary to reflect the changes
- [x] CI passes after rebase

### CODE REVIEW

**Comment by rajadain** [comment]
Taking a look now

**Review by rajadain — CHANGES_REQUESTED** [review]
Seeing a crash:

https://user-images.githubusercontent.com/1430060/198902614-3aaa19c8-8506-46d6-b64e-308f88b7f313.mp4

Steps to reproduce:

- Draw new polygon
- Go back to submissions list
- Click back into submission detail
- Crash

**Comment by mstone121** [comment]
> Seeing a crash:

This was caused by not saving a `type` field for the shape's geojson file. Django adds this info, so it's in the response from the API, but it wasn't in the manually updated RTK Query cache.

https://github.com/azavea/iow-boundary-tool/pull/169/commits/f0b0804df0feea4adf183462b6a743d08f7d8d7c

**Comment by rajadain** [comment]
Taking another look

**Review by rajadain — APPROVED** [review]
+1 tested, this is working well!

**Pull request merged**
