### PR TITLE
Document AWS Architecture

### LINKED ISSUE #230: Document AWS Architecture
## Overview

Similar to other projects, create a diagram of our AWS architecture, and document which pieces of it are setup in which terraform files.

Consider using [CloudCraft](https://www.cloudcraft.co/) or any of the solutions recommended by AWS for this: https://aws.amazon.com/architecture/icons/.

### PR DESCRIPTION
**Pull request by rajadain**
## Overview

Adds a new directory for creating and storing diagrams as code. This uses the Python [diagrams](https://diagrams.mingrammer.com/) package. All changes will be reflected in the `main.py` file. All diagrams are auto-generated from that file. Instructions for installation and generation are specified in the README.

Also adds diagrams to the deployment README. Finally, adds an AWS Architecture ADR describing the setup there.

Closes #230 

## Testing Instructions

- Read through the AWS Architecture ADR
  - [x] Ensure it reflects the true architecture of the project

## Checklist

- [x] `fixup!` commits have been squashed
- [x] `CHANGELOG.md` updated with summary of features or fixes, following [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines
- [ ] `README.md` updated if necessary to reflect the changes
- [ ] CI passes after rebase

### CODE REVIEW

**Comment by rajadain** [comment]
Clarified Python 3.6+ dependency, that this should be run locally and not in Docker, and pinned the version of `diagrams`, in [0ed1dd8](https://github.com/azavea/iow-boundary-tool/pull/231/commits/0ed1dd88debf15f11dc9e5afe9a50853aa05bedb)

**Review by JN-Hernandez — APPROVED** [review]
Looks good, great high-level view! +1

If you think it'll be beneficial, we may want to look towards creating a more detailed architectural diagram in the future, to include deeper information regarding access (AWS Identity and Access Management, IAM roles and permissions, etc) and networking (identifying public versus private subnets, routing tables, ACLs, etc) - something along the lines of:

example-aws-diagram

**Comment by rajadain** [comment]
Thank you! Did you make that diagram? What is it made in?

**Review by caseycesari — APPROVED** [review]
Makes sense to me. Nice job figuring out a way to do it via code.

**Comment by rajadain** [comment]
Thanks for reviewing! Will merge once green.

**Comment by JN-Hernandez** [comment]
> Thank you! Did you make that diagram? What is it made in?

I didn't make that example diagram, it's an example diagram from [SmartDraw](https://www.smartdraw.com/aws-diagram/) - a diagramming tool that has an AWS plug-in.  I've only briefly looked over the software and haven't used it yet.

**Pull request merged**
